# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax

    rate_limiter:
        login_throttling:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
